# template for a command line interface module __init__.py
# generated by cliq (version {cliq_version})

"""{name}: command line interface module
"""

__version__ = '0.0.0'
__version_info__ = tuple(
    int(i) for i in __version__.split('.') if i.isdigit()
)
