# generated by cliq (version {cliq_version})

"""main: entry-point"""

import cliq.main.cli

def main():
    """entry-point for console-script
    """
    app = cliq.main.cli.App(__package__)
    app.run()
    app.exit()

